# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Ashik Shafi
description: I write things which excites me..‚ù§
github_username: ashblogs08

# Email and twitter are optional:
email: ashikshafi0@gmail.com
twitter_username: AshikHafi
instagram_username: ashikshafi0
linkedin_username: Ashik Shaffi

# Set this to true to get LaTeX math equation support
use_math: True

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: UA-180453141-1

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
